### ISSUE TITLE
Add support for array of middlewares

### ISSUE THREAD

**Issue by matmar10** [biowink/express-route-versioning#10]
From [http://expressjs.com/en/guide/routing.html](http://expressjs.com/en/guide/routing.html)

> Route handlers can be in the form of a function, an array of functions, or combinations of both, as shown in the following examples.

```
app.use(express.Router().get('/api/people', version.reroute({
  1: [ passport.authenticate('bearer'), getAllPeopleV1 ],
  2: [ passport.authenticate('bearer'), getAllPeopleV2 ]
})));
```

Current behavior:
```
TypeError: Cannot call method 'some' of undefined
    at has_matching_route (/node_modules/express-route-versioning/lib/index.js:23:23)
    at /node_modules/express-route-versioning/lib/index.js:75:11
```

**Comment by matmar10** [comment]
Works as expected - was incorrect usage. Closing.
